apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewogICAgImdoY3IuaW8iOiB7CiAgICAgICJhdXRoIjogIllXNWtjbVYzTFdkMWNucG9hVHBuYVhSb2RXSmZjR0YwWHpFeFFVdEpOVFZEU1RCQ1NWWkdZelJOUXpGSWVFNWZkakZzUzNkbFNFZDNRWHA0U0VORlYzRkxSMHd3UjIwemJIVjBSekp2WTI1S2JXdExZbTlTYUhkbmVEZEVSVVJEV2xoV09GbHhhRUptVURVPSIKICAgIH0KICB9LAoJImNyZWRzU3RvcmUiOiAiZGVza3RvcCIsCgkiY3VycmVudENvbnRleHQiOiAiZGVza3RvcC1saW51eCIsCgkicGx1Z2lucyI6IHsKCQkiZGVidWciOiB7CgkJCSJob29rcyI6ICJleGVjIgoJCX0sCgkJInNjb3V0IjogewoJCQkiaG9va3MiOiAicHVsbCxidWlsZHggYnVpbGQiCgkJfQoJfSwKCSJmZWF0dXJlcyI6IHsKCQkiaG9va3MiOiAidHJ1ZSIKCX0KfQ==
type: kubernetes.io/dockerconfigjson
